server:
  port: 8080
  servlet:
    contextPath: /api/v1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USER}
    password: ${PASSWORD}

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: user-read-private, user-read-email
            redirect-uri: http://localhost:8080/api/v1/login/oauth2/code/spotify
            authorization-grant-type: authorization_code
            client-name: Spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

  logging:
    level:
      org:
        hibernate:
          SQL: debug
      org.springframework.security: DEBUG

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mail:
    username: ${example@email.com}
    password: ${password}
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true