name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

      - name: Execute checkstyleMain
        run: ./gradlew clean checkstyleMain
        working-directory: ${{ secrets.WORKING_DIRECTORY }}

      - name: Execute checkstyleTest
        run: ./gradlew clean checkstyleTest
        working-directory: ${{ secrets.WORKING_DIRECTORY }}